server:
  port: 0

spring:
  application:
    name: second-service

eureka:
  client:
    register-with-eureka: true # Eureka Server에 등록될지 여부
    fetch-registry: true # Eureka 서버로부터 인스턴스들의 정보를 주기적으로 가져올 것인지 여부
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance.id:${random.value}}
